version: '3.3'
services:
    db:
        image: postgres:9.6.2-alpine
        restart: always
        environment:
            # POSTGRES_PASSWORD: feedItUp
            POSTGRES_DB: feedbuzz
            POSTGRES_USER: feedbuzz
        ports:
            - "5430:5432"

